version: '3.9'



services:
  api:
    image: atvarsap/basic-webapp-api
    build: ./api
    labels:
      - "traefik.http.routers.api.rule=Host(`api.local`)"
      - traefik.http.services.api.loadbalancer.server.port=8080
      - "traefik.http.routers.api.middlewares=admin"
      - "traefik.docker.network=lab3_web"
    # ports:
    #   - 8080:8080
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${PORT}
    networks:
      - web
      - data
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - postgres.env


  frontend:
    image: atvarsap/basic-webapp-frontend
    build: ./web
    expose:
      - 5000

    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    labels:
      - traefik.enable=false
      - "traefik.docker.network=lab3_web"
    volumes:
      - ./web/webapp/static/:/app/webapp/static
    networks:
      - web
    env_file:
      - .frontend.env

  nginx:
    image: atvarsap/basic-webapp-nginx
    build: ./nginx
    # ports:
    #   - 80:80
    labels:
      - "traefik.http.routers.frontend.rule=Host(`frontend.local`)"
      - "traefik.docker.network=lab3_web"
    volumes:
      - ./web/webapp/static/:/app/static:ro
    networks:
      - web


  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    labels:
      - traefik.enable=false
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - data
    env_file:
      - postgres.env

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.11
    # Enables the web UI and tells Traefik to listen to docker
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.middlewares.admin.basicauth.users=atvars:$$2y$$05$$Tq7FdCYYZ9i0Y/oWefemMOl5mf4AW8ScAXjLSy/y/2pRsPhUYGNlS" #Username atvars, password atvars
      - "traefik.docker.network=lab3_web"
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"

    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

networks:
  web:
  data:

volumes:
  postgres:
